### ISSUE TITLE
Missing Categories Tab in TCA

### ISSUE THREAD

**Issue by hirnsturm** [TYPO3-extensions/metadata#2]
After installing of the extension the tab for choosing image categories is missing. I found out, that the following lines are lost after merging of TCA:
```
// Add category tab if categories column is present
if (isset($GLOBALS['TCA']['sys_file_metadata']['columns']['categories'])) {
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
		'sys_file_metadata',
		'--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category,categories'
	);
}
```

**Comment by fabarea** [comment]
You must install EXT:filemetadata first. Please notice, this repo is obsolete (git mirror), new repo is @ https://github.com/fabarea/metadata
